/**
 * Types of Step.
 * @readonly
 * @enum {number}
 */
export enum Step {
    DEPLOY_TOKEN_CONTRACT = 1,
    DEPLOY_AIRDROP_CONTRACT,
    CHECK_ACTIVE_WALLET_PERMISSIONS,
    GENERATE_MERKLE_TREE,
    AIRDROP_OWNER_SAVE_WHITELIST_ON_CHAIN,
    TOKEN_OWNER_APPROVE_ALLOWANCE,
    CLAIM_BY_A_WHITELIST_WALLET
}